{{- range .Values.imagePullSecrets }}  
{{- if and .registry .username .password .email }}  
apiVersion: v1  
kind: Secret  
metadata:  
  name: {{ .name }}  
type: kubernetes.io/dockerconfigjson  
data:  
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\" } } }" .registry .username .password .email | b64enc | quote }}  
---  
{{- end }}  
{{- end }}
